### ISSUE TITLE
Fix yellowboxes

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite-dev-screens#8]
Currently using two deprecated methods in NetInfo which cause yellowboxes.

Move to equivalent (and tested) alternatives.

**Comment by ruddell** [comment]
This was fixed already, but we still need an `npm publish` please

**Comment by GantMan** [comment]
released as 2.3.0 thanks!

**Comment by morgandonze** [comment]
Closing since @GantMan says fix was released
